apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: unauthorized-process-execution
  namespace: stackrox
spec:
  policyName: "[GitOps] Unauthorized Process Execution"
  description: "Runtime: alert when unexpected processes execute."
  severity: HIGH_SEVERITY
  categories: ["Anomalous Activity"]
  lifecycleStages: ["RUNTIME"]
  eventSource: DEPLOYMENT_EVENT
  policySections:
    - sectionName: "Unexpected process"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "sh"
            - value: "bash"
