apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: unauthorized-process-execution
  namespace: stackrox
spec:
  policyName: "[GitOps] Unauthorized Process Execution"
  description: "Runtime: alert when unexpected processes execute (baseline/anomaly use-case)."
  severity: HIGH_SEVERITY
  categories:
    - Anomalous Activity
  lifecycleStages:
    - RUNTIME
  disabled: false
  policySections:
    - sectionName: "placeholder"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "sh"
