apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: unauthorized-network-flow
  namespace: stackrox
spec:
  policyName: "[GitOps] Unauthorized Network Tool Execution"
  description: "Runtime: detect execution of common network tooling inside containers."
  severity: HIGH_SEVERITY
  disabled: false

  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT

  categories:
    - Network Activity

  process:
    - name: "curl"
    - name: "wget"
    - name: "nc"
    - name: "ncat"
    - name: "netcat"
