apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: unauthorized-network-flow
  namespace: stackrox
spec:
  policyName: "[GitOps] Unauthorized Network Tool Execution"
  description: "Runtime: alert when common network tools execute."
  severity: HIGH_SEVERITY
  categories: ["Network Activity"]
  lifecycleStages: ["RUNTIME"]
  eventSource: DEPLOYMENT_EVENT
  policySections:
    - sectionName: "Network tooling"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "curl"
            - value: "wget"
            - value: "nc"
