apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: linux-user-add-execution
  namespace: stackrox
spec:
  policyName: "Linux User Add Execution (GitOps)"
  severity: HIGH_SEVERITY
  disabled: false

  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT_EVENT

  categories:
    - System Modification

  process:
    - name: "useradd"
    - name: "adduser"
    - name: "usermod"
