apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: redhat-package-manager-execution
  namespace: stackrox
spec:
  policyName: "Red Hat Package Manager Execution (GitOps)"
  description: "Runtime: detect package manager usage inside containers."
  severity: MEDIUM_SEVERITY
  categories: ["System Modification"]
  lifecycleStages: ["RUNTIME"]
  eventSource: DEPLOYMENT_EVENT
  policySections:
    - sectionName: "Package managers"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "yum"
            - value: "dnf"
            - value: "rpm"
