apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: redhat-package-manager-execution
  namespace: stackrox
spec:
  policyName: "Red Hat Package Manager Execution (GitOps)"
  severity: MEDIUM_SEVERITY
  disabled: false

  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT_EVENT

  categories:
    - System Modification

  process:
    - name: "yum"
    - name: "dnf"
    - name: "rpm"
