apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: remote-file-copy-binary-execution
  namespace: stackrox
spec:
  policyName: "Remote File Copy Binary Execution (GitOps)"
  description: "Runtime: alert when remote copy tools run (scp/rsync/curl/wget)."
  severity: HIGH_SEVERITY
  categories:
    - Data Exfiltration
    - Anomalous Activity
  lifecycleStages:
    - RUNTIME
  disabled: false
  policySections:
    - sectionName: "remote-copy"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "scp"
            - value: "rsync"
            - value: "sftp"
            - value: "curl"
            - value: "wget"
