apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: k8s-actions-exec-into-pod
  namespace: stackrox
spec:
  policyName: "Kubernetes Actions: Exec into Pod (GitOps)"
  description: "Runtime: detect interactive shells often launched during kubectl/oc exec sessions."
  severity: HIGH_SEVERITY
  disabled: false

  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT

  categories:
    - Kubernetes Events

  process:
    - name: "sh"
    - name: "bash"
