apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: process-targeting-kubelet-endpoint
  namespace: stackrox
spec:
  policyName: "[GitOps] Process Targeting Cluster Kubelet Endpoint"
  description: "Runtime: detect suspicious network tooling that may be used to query kubelet endpoints from a container."
  severity: HIGH_SEVERITY
  categories:
  - Network Activity
  lifecycleStages:
  - RUNTIME
  disabled: false
  policySections:
  - sectionName: "kubelet-suspicious-tooling"
    policyGroups:
    - fieldName: "Process Name"
      values:
      - value: "curl"
      - value: "wget"
      - value: "nc"
      - value: "ncat"
