apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: process-targeting-kubelet-endpoint
  namespace: stackrox
spec:
  policyName: "[GitOps] Process Potentially Targeting Kubelet"
  description: "Runtime: detect tooling commonly used to query kubelet endpoints from containers."
  severity: HIGH_SEVERITY
  disabled: false

  lifecycleStages:
    - RUNTIME
  eventSource: DEPLOYMENT

  categories:
    - Network Activity

  process:
    - name: "curl"
    - name: "wget"
    - name: "nc"
    - name: "ncat"
