apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: process-targeting-kubelet-endpoint
  namespace: stackrox
spec:
  policyName: Process Targeting Cluster Kubelet Endpoint (GitOps)
  description: "Runtime: alert on access attempts to kubelet endpoints from workloads."
  severity: HIGH_SEVERITY
  categories:
    - Kubernetes
    - Lateral Movement
  lifecycleStages:
    - RUNTIME
  disabled: false
  policySections: []
