apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: process-targeting-kubelet-endpoint
  namespace: stackrox
spec:
  policyName: "[GitOps] Process Potentially Targeting Kubelet"
  description: "Runtime: detect tooling often used to query kubelet endpoints."
  severity: HIGH_SEVERITY
  categories: ["Network Activity"]
  lifecycleStages: ["RUNTIME"]
  eventSource: DEPLOYMENT_EVENT
  policySections:
    - sectionName: "HTTP tooling"
      policyGroups:
        - fieldName: "Process Name"
          values:
            - value: "curl"
            - value: "wget"
