apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: process-targeting-kubelet-endpoint
  namespace: stackrox
spec:
  policyName: "Process Targeting Cluster Kubelet Endpoint (GitOps)"
  description: "Runtime: alert on attempted access to kubelet endpoint (port 10250)."
  severity: HIGH_SEVERITY
  categories:
    - Kubernetes
    - Lateral Movement
  lifecycleStages:
    - RUNTIME
  disabled: false
  policySections:
    - sectionName: "kubelet-access"
      policyGroups:
        - fieldName: "Destination Port"
          values:
            - value: "10250"
